create_project vp "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/sandbox//vp"
set_property part xc7a35tcpg236-1 [current_project]
set_property target_language VHDL [current_project]
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/arith/Comparator_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/memory/LogisimCounter_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/memory/D_FLIPFLOP_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/memory/REGISTER_FLIP_FLOP_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/toplevel/logisimTopLevelShell_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/plexers/Multiplexer_2_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/plexers/Multiplexer_bus_2_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/signed_pwm4_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/Self_Timer_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/distance_counter16_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/Dance_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/FSM_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/gates/OR_GATE_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/gates/AND_GATE_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/gates/XOR_GATE_ONEHOT_entity.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/arith/Comparator_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/memory/REGISTER_FLIP_FLOP_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/memory/LogisimCounter_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/memory/D_FLIPFLOP_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/toplevel/logisimTopLevelShell_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/plexers/Multiplexer_2_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/plexers/Multiplexer_bus_2_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/FSM_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/distance_counter16_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/signed_pwm4_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/Self_Timer_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/circuit/Dance_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/gates/OR_GATE_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/gates/AND_GATE_behavior.vhd"
add_files "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/vhdl/gates/XOR_GATE_ONEHOT_behavior.vhd"
add_files -fileset constrs_1 "/home/kirill/logisim_evolution_workspace/Robot_Dance_FSM/Dance/xdc/vivadoConstraints.xdc"
exit
